[package]
name = "pellx_monitor"
version = "0.0.1"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
humantime = "2.3.0"
humantime-serde = "1.1"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
rppal = "0.16"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
